name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for reporting this issue, We will try our best to fix it!'' first issue'
        pr-message: 'Thanks for this PR, We really appreciate '' first pr'
